### ISSUE TITLE
Same issue, can't open images

### ISSUE THREAD

**Issue by franeknowak** [CAMMA-public/Endoscapes#3]
Hi. This looks like a great dataset, but I have the same issue as eighteenlin. I redownloaded the dataset three times to rule out any problems with the download on my end. The images in 12_5, 25, all and val_seg folders all have 1kb and cannot be opened. The ones in semseg, test, test_seg, train and val seem fine. I understand this may be caused by the symbolic links mentioned in the other issue, but I don't really know how to go around the problem.

System: Win11
Checked both through explorer, as well as using PIL

*edit*
I've looked into the problem further, and I suspect that the images are not treated as symlinks? (attached 3rd picture) 

Thanks a lot for help,
FMN
1. Opening with win explorer
![image](https://github.com/CAMMA-public/Endoscapes/assets/100887519/2beff44f-d656-4f4d-b311-8d269926f8e9)

2. Opening with PIL
![image](https://github.com/CAMMA-public/Endoscapes/assets/100887519/73a49a6e-bce6-41d2-8894-8323ec3f124f)

3. Checking symlink address
![image](https://github.com/CAMMA-public/Endoscapes/assets/100887519/20065d79-d05c-4f2d-ad0d-6fa0d755341a)

**Comment by adit98** [comment]
Hi, the issue is because the symlinks were created on a Linux-based filesystem and don't translate to Windows. You should be able to write a script to recreate the symlinks on your system. The original images are split between the `train`, `val` and `test` folders. You just need to replace each existing symlink-ed file with a new one that you create with the same name and the path of the original image (which will be in either `train`, `val`, or `test`). The splits are all done by video, and there are text files containing the video ids contained in each split if needed.

It is a bit odd that you can open the `test_seg` images but not the `val_seg` images. They should both consist of symlinks.

Hope this helps.

**Comment by franeknowak** [comment]
Thanks a lot, this really helped
