### ISSUE TITLE
Questions about missing data sets

### ISSUE THREAD

**Issue by xtlSJTU** [CAMMA-public/Endoscapes#6]
Hello author, 
as the dataset README.md describes that there is a 'train_seg' folder in the datasets, but according to the downloaded resources, this folder is not provided.
![20240703134923](https://github.com/CAMMA-public/Endoscapes/assets/138181330/1b20d70b-ff12-4605-a2de-a6f1a7ad2669)

**Comment by adit98** [comment]
Hi,

Apologies for the delay. The issue is because some of the folders/files are stored as symlinks (e.g. train_seg folder, train_seg_vids.txt file), which were created on a Linux based filesystem and do not work on Windows. You can recreate these symlinks locally and everything should work as expected. Please see https://github.com/CAMMA-public/Endoscapes/issues/3 for details.
